"""Initial migration for FinSense models

Revision ID: 7c3103a56472
Revises:
Create Date: 2026-10-10 11:21:54.903265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c3103a56472'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'suppliers',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('gstin', sa.String(length=15), nullable=True),
        sa.Column('legal_name', sa.String(length=255), nullable=True),
        sa.Column('trade_name', sa.String(length=255), nullable=True),
        sa.Column('state', sa.String(length=50), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('first_invoice_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('latest_invoice_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('invoice_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_purchase_value', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('average_purchase_value', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('identity_history', sa.JSON(), nullable=True),
        sa.Column('validation_failure_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('common_tax_rates', sa.JSON(), nullable=True),
        sa.Column('common_hsn_codes', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_gstin'), 'suppliers', ['gstin'], unique=True)
    op.create_index(op.f('ix_suppliers_legal_name'), 'suppliers', ['legal_name'], unique=False)
    op.create_index(op.f('ix_suppliers_first_invoice_date'), 'suppliers', ['first_invoice_date'], unique=False)
    op.create_index(op.f('ix_suppliers_latest_invoice_date'), 'suppliers', ['latest_invoice_date'], unique=False)
    op.create_index(op.f('ix_suppliers_state'), 'suppliers', ['state'], unique=False)

    op.create_table(
        'reminders',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('invoice_id', sa.String(length=36), nullable=False),
        sa.Column('rule_type', sa.String(length=20), nullable=False),
        sa.Column('interval_days', sa.Integer(), nullable=True),
        sa.Column('repeat_every_days', sa.Integer(), nullable=True),
        sa.Column('first_fire_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('next_fire_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=False, server_default='Asia/Kolkata'),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='scheduled'),
        sa.Column('calendar_sync_status', sa.String(length=20), nullable=False, server_default='not_connected'),
        sa.Column('notification_channels', sa.JSON(), nullable=True),
        sa.Column('google_calendar_id', sa.String(length=100), nullable=True),
        sa.Column('google_event_id', sa.String(length=100), nullable=True),
        sa.Column('idempotency_key', sa.String(length=64), nullable=False),
        sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
        sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_reminders_invoice_id'), 'reminders', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_reminders_next_fire_at'), 'reminders', ['next_fire_at'], unique=False)
    op.create_index(op.f('ix_reminders_status'), 'reminders', ['status'], unique=False)
    op.create_index(op.f('ix_reminders_calendar_sync_status'), 'reminders', ['calendar_sync_status'], unique=False)
    op.create_index(op.f('ix_reminders_idempotency_key'), 'reminders', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_idempotency_key'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_calendar_sync_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_next_fire_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_invoice_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_suppliers_state'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_latest_invoice_date'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_first_invoice_date'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_legal_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_gstin'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###